name: Docker Image CI
on:
  push:
    tags:
      - 'v[0-9].*'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true  
        default: 'warning'

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
    
    - name: Get Current date
      id: date
      run: echo "::set-output name=today::$(date + '%Y-%m-%d_%H-%M')"

    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2

    - name: Get available platforms
      run: echo ${{steps.buildx.outputs.platforms}}

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker Hub login
      uses: docker/login-action@v2
      with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}

    - name: Extract metadata (tags,labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: calhounchen/milkv-duo

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: ${{steps.meta.outputs.tags}}
        labels: ${{steps.meta.outputs.labels}}
